/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.xxdevplus.gui;

/**
 *
 * @author User
 */
public class XhtDbgDlg extends javax.swing.JDialog {

/**
 * Creates new form XhtDbgCtl
 */
public XhtDbgDlg(java.awt.Frame parent, boolean modal) {
 super(parent, modal);
 initComponents();
}

public boolean ChkShowXhtParserForEveryUrl()
{
 return chkShowXhtParserForEveryUrl.getModel().isSelected();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  chkShowXhtParserForEveryUrl = new javax.swing.JCheckBox();
  jCheckBox2 = new javax.swing.JCheckBox();
  jCheckBox3 = new javax.swing.JCheckBox();
  jCheckBox4 = new javax.swing.JCheckBox();
  jCheckBox5 = new javax.swing.JCheckBox();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
  setTitle("XmlHtmlTags Debug");

  chkShowXhtParserForEveryUrl.setSelected(true);
  chkShowXhtParserForEveryUrl.setText("show XhtParser for every url");

  jCheckBox2.setText("jCheckBox1");

  jCheckBox3.setText("jCheckBox1");

  jCheckBox4.setText("jCheckBox1");

  jCheckBox5.setText("jCheckBox1");

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(16, 16, 16)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(chkShowXhtParserForEveryUrl)
     .addComponent(jCheckBox2)
     .addComponent(jCheckBox3)
     .addComponent(jCheckBox4)
     .addComponent(jCheckBox5))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(18, 18, 18)
    .addComponent(chkShowXhtParserForEveryUrl)
    .addGap(18, 18, 18)
    .addComponent(jCheckBox2)
    .addGap(18, 18, 18)
    .addComponent(jCheckBox3)
    .addGap(18, 18, 18)
    .addComponent(jCheckBox4)
    .addGap(18, 18, 18)
    .addComponent(jCheckBox5)
    .addContainerGap(95, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
 /* Set the Nimbus look and feel */
 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
  */
 try {
  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
   if ("Nimbus".equals(info.getName())) {
    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    break;
   }
  }
 } catch (ClassNotFoundException ex) {
  java.util.logging.Logger.getLogger(XhtDbgDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (InstantiationException ex) {
  java.util.logging.Logger.getLogger(XhtDbgDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (IllegalAccessException ex) {
  java.util.logging.Logger.getLogger(XhtDbgDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 } catch (javax.swing.UnsupportedLookAndFeelException ex) {
  java.util.logging.Logger.getLogger(XhtDbgDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
 }
 //</editor-fold>
 //</editor-fold>
 //</editor-fold>
 //</editor-fold>

 /* Create and display the dialog */
 java.awt.EventQueue.invokeLater(new Runnable() {
 public void run() {
  XhtDbgDlg dialog = new XhtDbgDlg(new javax.swing.JFrame(), true);
  dialog.addWindowListener(new java.awt.event.WindowAdapter() {
  @Override
  public void windowClosing(java.awt.event.WindowEvent e) {
   System.exit(0);
  }
  });
  dialog.setVisible(true);
 }
 });
}

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JCheckBox chkShowXhtParserForEveryUrl;
 private javax.swing.JCheckBox jCheckBox2;
 private javax.swing.JCheckBox jCheckBox3;
 private javax.swing.JCheckBox jCheckBox4;
 private javax.swing.JCheckBox jCheckBox5;
 // End of variables declaration//GEN-END:variables
}
